name: Build and Deploy
on:
  push:
    branches:
      - main
  schedule:
      - cron: "0 7 * * 1-5"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
            persist-credentials: false
      - name: Install and Build
        run: |
          npm ci --omit=dev
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
#       - name: Send notification 🐘
#         uses: actionsflow/axios@v1
#         with:
#           url: https://ricard.social/api/v1/statuses
#           method: POST
#           bearer-token: ${{ secrets.BOT_NOTIFICATIONS_ACCESS_TOKEN }}
#           data: |
#             {
#               "status":"@ricard Daily news digest\n\nhttps://quicoto.github.io/news-digest/",
#               "visibility": "private",
#               "media_ids": []
#             }
